# Generated by Django 3.1.3 on 2020-11-16 13:40

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Принадлежность')),
                ('image', models.FileField(blank=True, null=True, upload_to='accessories_images/', verbose_name='Иконка')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Принадлежность',
                'verbose_name_plural': 'Принадлежности',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.FileField(blank=True, null=True, upload_to='comfort_images/', verbose_name='Иконка')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Услуги и удобства',
                'verbose_name_plural': 'Услуги и удобства',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, null=True, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attr_images/', verbose_name='Фото')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '270x240', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название достопримечательности')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
            },
        ),
        migrations.CreateModel(
            name='Guestroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(null=True, verbose_name='Номер комнаты')),
                ('beds_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество кроватей')),
                ('size', models.SmallIntegerField(blank=True, null=True, verbose_name='Размер комнаты')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('furniture', models.CharField(default='', max_length=256, null=True, verbose_name='Мебель')),
                ('side', models.CharField(choices=[('north', 'Север'), ('south', 'Юг'), ('west', 'Запад'), ('east', 'Восток')], default='north', max_length=50, null=True, verbose_name='Сторона')),
                ('default_price', models.IntegerField(default=0, help_text='Если в базе нет цен на период, указанный в брони, использовать эту цену для подсчета итоговой суммы.', verbose_name='Цена по умолчанию')),
                ('image', models.ImageField(blank=True, help_text='Будет показана первой, что увидит пользователь', null=True, upload_to='room_main_images', verbose_name='Фоновая картинка')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '370x240', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('accessories', models.ManyToManyField(blank=True, related_name='room_accessories', to='webapp.Accessories', verbose_name='Принадлежности')),
                ('comfort', models.ManyToManyField(blank=True, related_name='room_comforts', to='webapp.Comfort', verbose_name='Услуги и удобства')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название корпуса')),
                ('distance', models.CharField(default='', max_length=50, verbose_name='До озера')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('longitude', models.CharField(default='', max_length=50, verbose_name='Долгота')),
                ('latitude', models.CharField(default='', max_length=50, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Roominess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roominess', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вместительность номера(число)')),
                ('roominess_name', models.CharField(max_length=200, verbose_name='Вместительность номера')),
                ('price_from', models.PositiveIntegerField(default=0, verbose_name='Цены от')),
                ('image', models.ImageField(blank=True, null=True, upload_to='roominess_images', verbose_name='Фото')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '220x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вместительность номера',
                'verbose_name_plural': 'Вместительность номеров',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('description', models.TextField(verbose_name='Описание сервиса')),
                ('image', models.FileField(blank=True, null=True, upload_to='service_images/', verbose_name='Иконка')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервис',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TypeOfRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ServiceLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
            ],
            options={
                'verbose_name': 'Сервис на главном',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Фото')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '770x410', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_galleries', to='webapp.guestroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='С')),
                ('to_date', models.DateField(verbose_name='До')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('housing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='webapp.housing', verbose_name='Корпус')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='webapp.typeofroom', verbose_name='Тип номера')),
                ('roominess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='webapp.roominess', verbose_name='Вместительность')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='housing',
            name='types',
            field=models.ManyToManyField(related_name='housing', to='webapp.TypeOfRoom', verbose_name='Типы номеров'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='webapp.housing', verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='roominess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='webapp.roominess', verbose_name='Вмещаемость'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='room_services', to='webapp.Service', verbose_name='Сервис'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='webapp.typeofroom', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images', verbose_name='Фото')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='webapp.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
