# Generated by Django 2.2 on 2020-11-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201119_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestroom',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='webapp.RoomView', verbose_name='Вид'),
        ),
    ]
